name: ethaqapp
description: هي منصة سعودية تعمل في مجال البحث وتوفير المحامين المعتمدين والمرخصين وضمان التعاقد بين الاطراف والحقوق الماليه الخاصة بهم بشكل آمن ومضمون

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.9
  change_app_package_name: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_iconly: ^1.0.2
  device_preview: ^1.1.0
  intl_phone_field: ^3.1.0
  animated_custom_dropdown: ^1.2.2
  page_transition: ^2.0.9
  top_snackbar_flutter: ^3.0.0+1
  pin_code_fields: ^7.4.0
  focused_menu: ^1.0.5
  flutter_svg: ^1.1.6
  file_picker: ^5.2.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.1
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/4.0x/app_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/image/4.0x/app_logo.png
  android: true
  ios: true
  fullscreen: true

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon_launcher.png"

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/translation/
    - assets/image/app_logo.png
    - assets/image/intro1.png
    - assets/image/intro2.png
    - assets/image/intro3.png
    - assets/image/choose_sign_image.png
    - assets/image/logo_without_text.png
    - assets/image/slider_home_lawyers.png
    - assets/image/consulting_icon.png
    - assets/image/element_plus.png
    - assets/image/avatar_image.png
    - assets/image/svg_images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
